[profile.default]
src = "src"
out = "output"
libs = ['lib']
solc_version = "0.8.19"
fs_permissions = [{ access = "read-write", path = "./deploy" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
tab_width = 4
line_length = 120
wrap_comments = true
bracket_spacing = true
override_spacing = true
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'attributes_first'
ignore = []

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
local = "http://127.0.0.1:8545"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
